name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci
      
      - name: Create config file
        run: |
          touch config.js
          echo "module.exports = { voiceRssApiKey: '${{ secrets.VITE_VOICERSS_API_KEY }}' }" > config.js
      
      - name: Build
        run: npm run build
        env:
          VITE_VOICERSS_API_KEY: ${{ secrets.VITE_VOICERSS_API_KEY }}
      
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist